### ISSUE TITLE
Make bread crumps active

### ISSUE THREAD

**Issue by ZU3AIRE** [ZU3AIRE/mark-me#7]
### Changes Required

The bread crumps does not update according to the current page, 
make them dynamic and add clickable functionality, so that clinking them updates the route

![image](https://github.com/user-attachments/assets/f2694741-7fb4-46ea-a9e1-63e442359aeb)

Remove this lightening icon from bottom left corner

![image](https://github.com/user-attachments/assets/ac509784-5c61-4ed5-b35c-36df187d0055)

### Acceptance Criteria 

- User navigates to the attendance route 
- The bread crumps should be updated accordingly `Attendance \ Mark Attendance` 
- Upon clicking Attendance from bread crump user should be navigated to the dashboard

- The lightening symbol should never appear again

**Comment by muhammad-mousa** [comment]
Unable to find the static routes icon So moving this to a new issue #11
